### ISSUE TITLE
Error "configparser.NoOptionError: No option 'ui_density_override' in section: 'carvera'" on startup

### ISSUE THREAD

**Issue by scottyallen** [Carvera-Community/Carvera_Controller#112]
On the develop branch, I'm getting the below error on startup.  I checked out 33bc9332294693a38e7a1165db6e6ee6973c3715 and it had the same issue, but checking out 7e83c2731a6724f7ae8d0db0c147ca17798cb831 not only fixed it, but when I checked out HEAD again, it worked.

` Traceback (most recent call last):
   File "/Users/scotty/.pyenv/versions/3.12.4/lib/python3.12/configparser.py", line 767, in get
     value = d[option]
             ~^^^^^^^^
   File "/Users/scotty/.pyenv/versions/3.12.4/lib/python3.12/collections/__init__.py", line 1015, in __getitem__
     return self.__missing__(key)            # support subclasses that define __missing__
            ^^^^^^^^^^^^^^^^^^^^^
   File "/Users/scotty/.pyenv/versions/3.12.4/lib/python3.12/collections/__init__.py", line 1007, in __missing__
     raise KeyError(key)
 KeyError: 'ui_density_override'

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "<frozen runpy>", line 198, in _run_module_as_main
   File "<frozen runpy>", line 88, in _run_code
   File "/Users/scotty/Dropbox (Personal)/code/Carvera_Controller/carveracontroller/__main__.py", line 8, in <module>
     main()
   File "/Users/scotty/Dropbox (Personal)/code/Carvera_Controller/carveracontroller/main.py", line 3845, in main
     load_app_configs()
   File "/Users/scotty/Dropbox (Personal)/code/Carvera_Controller/carveracontroller/main.py", line 3751, in load_app_configs
     if Config.get('carvera', 'ui_density_override') == "1":
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/Users/scotty/Library/Caches/pypoetry/virtualenvs/carvera-controller-community-_I5kigNb-py3.12/lib/python3.12/site-packages/kivy/config.py", line 541, in get
     value = PythonConfigParser.get(self, section, option, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/Users/scotty/.pyenv/versions/3.12.4/lib/python3.12/configparser.py", line 770, in get
     raise NoOptionError(option, section)
 configparser.NoOptionError: No option 'ui_density_override' in section: 'carvera'`

**Comment by scottyallen** [comment]
I suspect this has something to do with adding new config options to the user's config file, but I'm not positive.

**Comment by scottyallen** [comment]
Ah, no scratch that.  It doesn't work at HEAD for me.
