### ISSUE TITLE
Malformed config files hang controller

### ISSUE THREAD

**Issue by faecorrigan** [Carvera-Community/Carvera_Controller#92]
When the controller is connecting to a machine with a malformed config file it will download config, try to sync version and time, then hang with the error at the bottom of this issue

For example the sample file has a space in main_button_long_press_enable

![image](https://github.com/user-attachments/assets/a021623b-23ce-4af3-baca-0ae566c12408)

![image](https://github.com/user-attachments/assets/b0257527-2f14-4901-a439-b14858d477da)

Traceback (most recent call last):
  File "makera.py", line 4071, in <module>
  File "kivy\app.py", line 956, in run
  File "kivy\base.py", line 574, in runTouchApp
  File "kivy\base.py", line 339, in mainloop
  File "kivy\base.py", line 379, in idle
  File "kivy\clock.py", line 733, in tick
  File "kivy\clock.py", line 776, in post_idle
  File "kivy\\_clock.pyx", line 620, in kivy._clock.CyClockBase._process_events
  File "kivy\\_clock.pyx", line 653, in kivy._clock.CyClockBase._process_events
  File "kivy\\_clock.pyx", line 649, in kivy._clock.CyClockBase._process_events
  File "kivy\\_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
  File "makera.py", line 4065, in switch_to_main
  File "kivy\app.py", line 956, in run
  File "kivy\base.py", line 574, in runTouchApp
  File "kivy\base.py", line 339, in mainloop
  File "kivy\base.py", line 379, in idle
  File "kivy\clock.py", line 733, in tick
  File "kivy\clock.py", line 776, in post_idle
  File "kivy\\_clock.pyx", line 620, in kivy._clock.CyClockBase._process_events
  File "kivy\\_clock.pyx", line 653, in kivy._clock.CyClockBase._process_events
  File "kivy\\_clock.pyx", line 649, in kivy._clock.CyClockBase._process_events
  File "kivy\\_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
  File "makera.py", line 2315, in finishLoadConfig
AttributeError: 'NoneType' object has no attribute 'strip'

[config.txt](https://github.com/user-attachments/files/17936718/config.txt)

**Comment by SergeBakharev** [comment]
this issue can be reproduced by setting a machine config value like this:
`config-set sd main_button_long_press_enable 'Tool Change'`
